### ISSUE TITLE
[SOLVED] What means  reimage = true ?

### ISSUE THREAD

**Issue by Hello23-Ygopro** [247321453/DataEditorX#12]
I tried to translate what it is inside the changed.txt , but i dont understand what exactly it is

Does anyone here know what that option does ?
########################### Artwork
reimage = true

Thank You!

**Comment by 247321453** [comment]
reimage  is auto zoom image.
自动缩放图片，再导入MSE存档

**Comment by Hello23-Ygopro** [comment]
Thank You for the explaination ,
Solved
