### ISSUE TITLE
Error: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by BeyondTheHorizon** [247321453/DataEditorX#20]
This happens when I try to export a card(s) as an MSE file while I selected the images from an image path.
![error](https://cloud.githubusercontent.com/assets/20503303/25094516/59416d20-238f-11e7-9209-00b3a06815a5.png)

**Comment by BeyondTheHorizon** [comment]
I should also add that this only happens on the latest version of DataEditorX i.e. it worked on previous versions.

**Comment by DailyShana** [comment]
fixed in ad2c0d1

**Comment by BeyondTheHorizon** [comment]
@DailyShana Thanks for the fix. This may now be closed.
