### ISSUE TITLE
Editor not opening cdb when clicking cdb

### ISSUE THREAD

**Issue by GameMaster719** [247321453/DataEditorX#22]
Hi there,
so yesterday i updated my DataEditorX to the newest available version. After doing so i noticed that when  i would click a cdb saved on the desktop for example, it would not open DataEditorX... it does however open them if say i go to file+open then select the file from any location.. 

Also if i try right clicking a cdb and selecting open with: after browsing my DataEditorX in its file location and selecting it... it don't set it as the default program to open with. After selecting it and pressing ok, it don't even appear on the list of possible programs to open the cdb. the older version for me didn't seem to cause this issue. not sure if the zip is missing something that is affecting the shortcuts for DataEditorX or human error on my end ? (All my other shortcuts on my computer seem to work... its just the cdb/opening with DataEdtiorX.) either way... it be greatly appreciated if you can help me to solve this issue. Thanks.

**Comment by DailyShana** [comment]
It is a file association issue, not related to DataEditorX itself.
