### ISSUE TITLE
Is it possible to port this Software into Linux ?

### ISSUE THREAD

**Issue by azispratama92** [247321453/DataEditorX#7]
Hello, thanks for such a wonderful software, i want to port this programs into GNU/Linux Os, is that possible? if that so how to do that ? Thanks :)

**Comment by DailyShana** [comment]
Maybe you can try [Mono](http://www.mono-project.com), but I'm not famillar with it.

**Comment by 247321453** [comment]
need win32 api

**Comment by azispratama92** [comment]
Yes, i can run your software with Mono.  wait i'll provide the screen capture about it

**Comment by azispratama92** [comment]
https://youtu.be/ikcm3rN5YtI

That one, that's for your quick reply buddy,
