### ISSUE TITLE
[ SOLVED ] Multiple Attributes & Races + More Search Fields

### ISSUE THREAD

**Issue by Hello23-Ygopro** [247321453/DataEditorX#8]
hi ,
Pretty cool how far this program has come ..
I really can't think of anything else that's missing at the moment , except  :
很酷這個程序有多遠..
我真的不能想到目前缺少的其他任何東西，除了： 
- 1. Inserting multiple Attributes (Property) & Monster Types , as seen here : 
- 1. 插入多個屬性（屬性）和怪物類型，如下所示： : 

![](http://i.imgur.com/zFC99uw.png)
The only way to do it is make the Attribute & Race fields empty and edit them in SQL by adding their Constant's hex values , but it would be nice to avoid the longer approach & have a check field perhaps , like the Card type & Category have their own check fields , to be able to add multiple Races & Attributes
唯一的方法是使屬性和種族字段為空，並通過添加其常數的十六進制值在SQL中編輯它們，但是避免更長的方法和一個檢查字段可能是很好的，如卡類型和類別 它們自己的檢查字段，以便能夠添加多個Races＆Attributes

I suppose another way , is to add it in Custom Card's scripts , with EFFECT_ADD_RACE or EFFECT_ADD_ATTRIBUTE with EFFECT_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE , so maybe this isn't needed ..
我想另一種方式，是將它添加到自定義卡的腳本，與EFFECT_ADD_RACE或EFFECT_ADD_ATTRIBUTE與EFFECT_CANNOT_DISABLE +效果標誌UNCOPYABLE，所以也許這不是必需的。
- 2. Adding a way to search for key words in a card's effect
- 2. 添加一種方法來搜索卡片效果中的關鍵字

I know u can search for specific cards in the database by just typing it here : 
我知道你可以在數據庫中搜索特定的卡，只需在這裡鍵入：
![](http://i.imgur.com/DzmTxwB.png)

Would it be possible to also add a way to search for cards by typing specific key words , like you can in Ygopro ?
是否可以通過鍵入特定的關鍵詞來添加一種方法來搜索卡片，就像在Ygopro中一樣？
![](http://i.imgur.com/EVL13V9.png)

i don't always want to use Ygopro to search for key words , especially after some "genius" thought it was "smart" to add a 4000+ card mandatory anime database , to make Ygopro load even longer than it did before , and the Ygopro Percy becomes more bugged after each update - u can't even search for pendulum scales and the sort button is all messed up , so i would rather use DataEditorX to search for cards
i just use Ygopro Percy to search for cards , so if i can look for them in DataEditorX , i won't have to use Ygopro Percy any more :dancer:
我不總是想使用Ygopro搜索關鍵詞，尤其是在一些“天才”認為它是“聰明”添加一個4000+卡強制性動畫數據庫，使Ygopro加載比以前，和 Ygopro Percy在每次更新後變得更多bug - u甚至不能搜索擺比例和排序按鈕都搞亂了，所以我寧願使用DataEditorX搜索卡
我只是使用Ygopro Percy搜索卡，所以如果我可以在DataEditorX中找到他們，我不必使用Ygopro Percy任何更多 :dancer:

Thank in advance
預先感謝

**Comment by 247321453** [comment]
setcode

**Comment by 247321453** [comment]
直接编辑cardinfo_english.txt，这样直观。添加 setname的频率太低了，没必要添加 add 1 dragon

**Comment by DailyShana** [comment]
Edit cardinfo_english.txt, change
```
##attribute
0x0	Attribute
0x1	Earth
0x2	Water
0x4	Fire
0x8	Wind
0x10	Light
0x20	Dark
0x40	Divine
```
to
```
##attribute
0x0	Attribute
0x1	Earth
0x2	Water
0x4	Fire
0x8	Wind
0x10	Light
0x20	Dark
0x40	Divine
0x3 Earth+Water
```
if you want to add a Earth+Water attribute.
Since there is no monster that has multiple original attribute at present, we are not going to improve this.

**Comment by DailyShana** [comment]
to search key words in card effect, click Reset button, type you key words in the blank card effect textbox: 
![image](https://cloud.githubusercontent.com/assets/8469304/21285994/0862090c-c483-11e6-9785-3b1df61248c2.png)
Then click Search button.

BTW, I think you don't need translate into Chinese by google translation.

**Comment by Hello23-Ygopro** [comment]
Thanks , i was a little late , but i figured out how to register multiple races awhile ago
i even added this to my .txt for my friends custom level 12+ monsters : 
http://i.imgur.com/BXuCrF7.png

Thanks for the updates , finally i can use Dataeditorx to search for keywords , because the current English Ygopros are : 
1 ) outdated,
2 ) slow
3 ) bugged
And if i search in Dataeditorx i can work faster
This is all very helpful for me and my friends projects , 

Thank You!
