### ISSUE TITLE
Support for non-ASCII characters.

### ISSUE THREAD

**Issue by KServantes** [247321453/DataEditorX#9]
Hi, trying to translate into Spanish and it seems that some special characters (¡, ¿, é, ú, etc.) do not come out well. Please add support for non-ASCII character for translating into other languages. 
![captura](https://cloud.githubusercontent.com/assets/24261853/21002881/4e83f080-bce5-11e6-8915-a2b6188139c8.PNG)

**Comment by DailyShana** [comment]
![image](https://cloud.githubusercontent.com/assets/8469304/21005672/a88d3646-bd70-11e6-89ab-4a00bd4016d5.png)
Maybe you need to save language_spanish.txt in UTF-8 format.

**Comment by KServantes** [comment]
![captura](https://cloud.githubusercontent.com/assets/24261853/21010528/c97f9950-bd09-11e6-8b99-924b7ee2b22a.PNG)
Ah, yes, that did it. Thanks for clearing it up!
